# Nom de votre projet
# (utilisez un seul mot, exemple: 'monprojet')
PROJECTNAME=testLib

# Fichiers sources
# Utilisez le suffixe .cpp pour les fichiers C++
# Listez tous les fichiers a compiler, separes par
# un espace. exemple: 'tp1.c tp2.cpp':
SRCDIR=.
PRJSRC=$(wildcard $(SRCDIR)/*.cpp) $(wildcard $(SRCDIR)/*.c)

# Inclusion du Makefile de configuration
include ../Makefile